CREATE USER ebw
IDENTIFIED BY pass
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to ebw;
GRANT resource to ebw;
GRANT create session TO ebw;
GRANT create table TO ebw;
GRANT create view TO ebw;



conn ebw/pass

CREATE TABLE CUSTOMER(
ACCT_NUM INTEGER PRIMARY KEY,
PASS VARCHAR2(50),
F_NAME VARCHAR2(50),
L_NAME VARCHAR2(50)
);

CREATE TABLE EMP(
ACCT_NUM INTEGER PRIMARY KEY,
PASS VARCHAR2(50)
);

CREATE TABLE OFFER(
ACCT_NUM INTEGER,
CAR_ID INTEGER,
AMOUNT_OFF INTEGER
);

CREATE TABLE CAR(
CAR_ID INTEGER PRIMARY KEY,
CAR_MAKE VARCHAR2(50),
CAR_MODEL VARCHAR2(50),
CAR_COLOR VARCHAR2(50),
CAR_OWNER INTEGER DEFAULT 0
);

CREATE TABLE PAYMENT(
CAR_ID INTEGER PRIMARY KEY,
ACCT_NUM INTEGER,
ORG_AMOUNT INTEGER,
AMT_LEFT INTEGER,
PAY_LEFT INTEGER DEFAULT 12
);

INSERT INTO EMP VALUES(100, 'pass');
COMMIT;

INSERT INTO EMP VALUES(300, 'pass');
COMMIT;

CREATE OR REPLACE PROCEDURE MYEMPPRO
(ACCT IN INTEGER, PASS IN VARCHAR2)
AS
BEGIN
INSERT INTO EMP VALUES(ACCT,PASS);
COMMIT;
END;
/

ALTER TABLE OFFER ADD OFFER_ID INTEGER;

ALTER TABLE OFFER 
ADD CONSTRAINT PK_OFFER 
PRIMARY KEY(OFFER_ID);
COMMIT;

ALTER TABLE OFFER ADD OFFER_STATUS VARCHAR2 (50);
